import ipaddress
import os
import shlex
import subprocess
from pathlib import Path

from database import get_waf_blocklist


RULE_PATH = Path(os.getenv("WAF_BLOCKLIST_RULE_PATH", "config/waf/ip-blocklist.conf"))
RULE_ID = int(os.getenv("WAF_BLOCKLIST_RULE_ID", "1001000"))
RELOAD_COMMAND = os.getenv("WAF_RELOAD_COMMAND", "docker exec sls_waf nginx -s reload")


def normalize_ip(value):
    raw = str(value or "").strip()
    if not raw:
        raise ValueError("IP is required")
    try:
        if "/" in raw:
            return str(ipaddress.ip_network(raw, strict=False))
        return str(ipaddress.ip_address(raw))
    except ValueError as exc:
        raise ValueError("Invalid IP or CIDR") from exc


def render_blocklist_rules(entries):
    ips = [normalize_ip(entry["ip"]) for entry in entries]
    lines = [
        "# Auto-generated by Shift-Left-Sync. Do not edit manually.",
        "# Source of truth: SQLite waf_ip_blocklist table.",
    ]

    if not ips:
        lines.append("# No blocked IPs.")
        return "\n".join(lines) + "\n"

    ip_match = ",".join(ips)
    lines.extend(
        [
            f'SecRule REMOTE_ADDR "@ipMatch {ip_match}" \\',
            (
                f'  "id:{RULE_ID},phase:1,deny,status:403,log,auditlog,'
                "msg:'SLS custom IP blocklist'"
                '"'
            ),
        ]
    )
    return "\n".join(lines) + "\n"


def write_blocklist_rules():
    entries = get_waf_blocklist()
    RULE_PATH.parent.mkdir(parents=True, exist_ok=True)
    RULE_PATH.write_text(render_blocklist_rules(entries), encoding="utf-8")
    return {"path": str(RULE_PATH), "count": len(entries)}


def reload_waf():
    if not RELOAD_COMMAND.strip():
        return {"ok": False, "skipped": True, "message": "WAF_RELOAD_COMMAND is empty"}

    args = shlex.split(RELOAD_COMMAND)
    try:
        completed = subprocess.run(args, capture_output=True, text=True, timeout=20)
    except FileNotFoundError as exc:
        return {"ok": False, "error": str(exc), "command": RELOAD_COMMAND}
    except subprocess.TimeoutExpired:
        return {"ok": False, "error": "reload command timed out", "command": RELOAD_COMMAND}

    return {
        "ok": completed.returncode == 0,
        "returncode": completed.returncode,
        "stdout": completed.stdout.strip(),
        "stderr": completed.stderr.strip(),
        "command": RELOAD_COMMAND,
    }


def sync_waf_blocklist(reload=True):
    result = {"rules": write_blocklist_rules()}
    if reload:
        result["reload"] = reload_waf()
    return result
